### ISSUE TITLE
VectorFieldLines(VDF2D) makes Renderer(DX11) stop working and sometimes Windows Blue Screen 

### ISSUE THREAD

**Issue by juanhurle** [everoneishappy/FieldTrip#5]
Hi! 
First of all thanks for the excellent library! been having loads of fun with it.
I´m having an issue with VectorFieldLines(VDF2D) and my new laptop (Lenovo Legion, NVIDIA Rtx 2070 ) in both vvvv beta 39 and 38.1 
With my previous laptop, a macbook pro late 2010 running bootcamp and vvvv 38.1 was working just fine. 
So every time I connect VectorFieldLines(VDF2D) to a Renderer(DX11) it makes the whole screen blackout for a few seconds and when it comes back, the renderer output is frozen, sometimes it makes vvvv crash and sometimes it makes Windows go into Blue screen of death! 

Any ideas what it could be happening? 
Thanks a lot!
Best

Juan Hurle

**Comment by everyoneishappy** [comment]
Hi Juan,
The difference between machine is most likely a graphics driver version.  Please note with both this and Instance noodles it's recommended  to use the studio drivers.  

Having said that, it's still obviously not ideal to have situations like that!  It's a little hard for me to check since I don't have the problem, but would you mind having a look if this fixes it before updating your drivers?
https://github.com/everyoneishappy/FieldTrip/commit/8f42d6f91e8eb05e1df6a2caa5c64304a6dde817

**Comment by juanhurle** [comment]
Hi Kyle! 
wow that fixes it! it now seems to run without a problem! Thanks a lot for the extremely fast response and solution !
one last question though, where Is the best to post general usage questions of both Fieldtrip and instance noodles?

all the best and once again thanks a lot for your time and effort!

J

**Comment by everyoneishappy** [comment]
Cool, glad that worked.  I would still highly recommend to use the studio drivers if possible- have had other issues that were only resolved that way.

General usage stuff- here or probably on vvvv.org, or just contact me directly.
